name: Build & Deploy Spring Boot

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy HTML web page analyzer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven

      - name: Unit tests
        run: mvn -B test --file pom.xml

      - name: Build the application
        run: |
          mvn clean 
          mvn -B package --file pom.xml